### PR TITLE
Setup Tests

### LINKED ISSUE #4: Write tests
Setup test suites for the project:

- Unit 
- Integration

Grab an example container and image response in json to use as reference while asserting

### PR DESCRIPTION
**Pull request by jcs98**
Fixes #4 

- Setup ts-jest
- Write first test for Image.isUpdatedImage

image

### CODE REVIEW

**Review by utkarsh867 — APPROVED** [review]

**Comment by VibhorCodecianGupta** [comment]
@jcs98 could you please make this PR to the `dev` branch instead? You've made it to the `master`. We can merge code into master once we've thoroughly tested and are ready for a release

**Review by utkarsh867 — APPROVED** [review]

**Comment by VibhorCodecianGupta** [comment]
@jcs98 tests look good. can you push container tests as well? we'll merge them together then

**Review by VibhorCodecianGupta — APPROVED** [review]

**Comment by jcs98** [comment]
@VibhorCodecianGupta that's great!
@sarthakkundra has taken up the container tests

**Comment by jcs98** [comment]
@VibhorCodecianGupta I have fixed the issues and rebased to the latest changes on dev

image

**Pull request merged**
